[build-system]
requires = ["setuptools >= 40.8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "xzonn-mt-tools"
version = "0.1.2"
requires-python = ">= 3.12"
authors = [
  {name = "Xzonn", email = "Xzonn@outlook.com"},
]
readme = "README.md"
license = {file = "LICENSE"}
